const path = require('path');
const fs = require('fs');

// Auto-locate .env by walking up directories — works wherever you run the script from
const findEnv = () => {
  let dir = __dirname;
  for (let i = 0; i < 5; i++) {
    const candidate = path.join(dir, '.env');
    if (fs.existsSync(candidate)) return candidate;
    dir = path.dirname(dir);
  }
  return null;
};
const envPath = findEnv();
if (!envPath) { console.error('❌ Could not find .env file'); process.exit(1); }
require('dotenv').config({ path: envPath });
console.log(`✅ Loaded .env from: ${envPath}`);

const AWS = require('aws-sdk');

AWS.config.update({
  region: process.env.AWS_REGION,
  accessKeyId: process.env.AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
});

const dynamoDB = new AWS.DynamoDB.DocumentClient();
const s3 = new AWS.S3();

const TABLE = process.env.SONGS_TABLE || 'Songs';
const BUCKET = process.env.S3_BUCKET;

// ─── SONG DEFINITIONS ────────────────────────────────────────────────────────
// moods stored as [{ S: "..." }] to match DynamoDB schema shown in console

const songs = [
  // ── A ──────────────────────────────────────────────────────────────────────
  {
    songId: 'song_001',
    name: 'Aahista Aahista',                       
    artist: 'Vishal-Shekhar, Lucky Ali',
    album: 'Bachna Ae Haseeno',
    description: 'A gentle, slow-burn romantic track with soft vocals and breezy instrumentation that captures the feeling of falling in love gradually.',
    moods: [{ S: 'Romantic' }, { S: 'Calm' }, { S: 'Dreamy' }, { S: 'Nostalgic' }],
    filePath: path.join(__dirname, 'songs', 'Aahista Aahista_spotdown.org.m4a'),
  },
  {
    songId: 'song_002',                              
    name: 'Aaj Kal Zindagi',
    artist: 'Shankar-Ehsaan-Loy',
    album: 'We Are Family',
    description: 'An upbeat, feel-good family anthem brimming with warmth, joy, and the celebration of everyday life.',
    moods: [{ S: 'Happy' }, { S: 'Uplifting' }, { S: 'Energetic' }, { S: 'Cheerful' }],
    filePath: path.join(__dirname, 'songs', 'Aaj Kal Zindagi_spotdown.org.m4a'),
  },
  {
    songId: 'song_003',
    name: 'Aaj Ki Raat',
    artist: 'Alisha Chinai, Mahesh Shetty',
    album: 'Don',
    description: 'A pulsating, high-energy dance number with sensual undertones, perfect for late-night parties and bold moods.',
    moods: [{ S: 'Energetic' }, { S: 'Bold' }, { S: 'Sensual' }, { S: 'Party' }],
    filePath: path.join(__dirname, 'songs', 'Aaj Ki Raat_spotdown.org.m4a'),
  },
  {
    songId: 'song_004',
    name: 'Aaja Khatam Sabr',
    artist: 'Sunidhi Chauhan',
    album: 'Ghost',
    description: "An intense, emotionally charged track expressing impatience and longing, driven by Sunidhi Chauhan's powerful vocals.",
    moods: [{ S: 'Intense' }, { S: 'Longing' }, { S: 'Passionate' }, { S: 'Restless' }],
    filePath: path.join(__dirname, 'songs', 'Aaja Khatam Sabr_spotdown.org.m4a'),
  },
  {
    songId: 'song_005',
    name: 'AANKH',
    artist: 'Sunidhi Chauhan',
    album: 'AANKH',
    description: "A bold and fierce track with a strong beat and attitude-driven lyrics, showcasing Sunidhi's raw power.",
    moods: [{ S: 'Bold' }, { S: 'Fierce' }, { S: 'Confident' }, { S: 'Energetic' }],
    filePath: path.join(__dirname, 'songs', 'AANKH_spotdown.org.m4a'),
  },
  {
    songId: 'song_006',
    name: 'Aap Ki Nazron Ne Samjha',
    artist: 'Sanam',
    album: 'Rewind With Sanam',
    description: 'A timeless romantic classic reimagined with soothing modern arrangements, conveying deep unspoken love through tender melodies.',
    moods: [{ S: 'Romantic' }, { S: 'Sentimental' }, { S: 'Nostalgic' }, { S: 'Calm' }],
    filePath: path.join(__dirname, 'songs', 'Aap Ki Nazron Ne Samjha_spotdown.org.m4a'),
  },
  {
    songId: 'song_007',
    name: 'Aapka Kya Hoga (Dhanno)',
    artist: 'Mika Singh, Sunidhi Chauhan',
    album: 'Housefull',
    description: 'A raucous, comedic item number that is infectiously fun, playful, and made for dancing with exaggerated energy.',
    moods: [{ S: 'Fun' }, { S: 'Playful' }, { S: 'Party' }, { S: 'Energetic' }],
    filePath: path.join(__dirname, 'songs', 'Aapka Kya Hoga (Dhanno)_spotdown.org.m4a'),
  },
  {
    songId: 'song_008',
    name: 'Abhi Abhi',
    artist: 'KK',
    album: 'Jism 2',
    description: "A hauntingly beautiful track about fresh heartbreak, with KK's soulful voice carrying an ache of love just discovered and already lost.",
    moods: [{ S: 'Heartbreak' }, { S: 'Melancholic' }, { S: 'Soulful' }, { S: 'Romantic' }],
    filePath: path.join(__dirname, 'songs', 'Abhi Abhi_spotdown.org.m4a'),
  },
  {
    songId: 'song_009',
    name: 'Achha Lagta Hai',
    artist: 'Shankar-Ehsaan-Loy',
    album: 'Aarakshan',
    description: 'A warm, feel-good track that radiates positivity and contentment, celebrating the simple pleasures of life.',
    moods: [{ S: 'Happy' }, { S: 'Content' }, { S: 'Uplifting' }, { S: 'Cheerful' }],
    filePath: path.join(__dirname, 'songs', 'Achha Lagta Hai_spotdown.org.m4a'),
  },
  {
    songId: 'song_010',
    name: 'Ae Dil Hai Mushkil Title Track',
    artist: 'Pritam, Arijit Singh',
    album: 'Ae Dil Hai Mushkil',
    description: "A sweeping unrequited love anthem — Arijit Singh's voice aches with longing over lush orchestration that captures one-sided love perfectly.",
    moods: [{ S: 'Heartbreak' }, { S: 'Longing' }, { S: 'Melancholic' }, { S: 'Romantic' }],
    filePath: path.join(__dirname, 'songs', 'Ae Dil Hai Mushkil Title Track (From _Ae Dil Hai Mushkil_)_spotdown.org.m4a'),
  },
  {
    songId: 'song_011',
    name: 'Agar Main Kahoon',
    artist: 'Shankar-Ehsaan-Loy',
    album: 'Lakshya',
    description: 'A soft, earnest love declaration wrapped in acoustic warmth, capturing the nervous vulnerability of expressing feelings for the first time.',
    moods: [{ S: 'Romantic' }, { S: 'Tender' }, { S: 'Hopeful' }, { S: 'Calm' }],
    filePath: path.join(__dirname, 'songs', 'Agar Main Kahoon_spotdown.org.m4a'),
  },
  {
    songId: 'song_012',
    name: 'Agar Tum Mil Jao',
    artist: 'Shreya Ghoshal',
    album: 'Zeher',
    description: "A dreamy, longing ballad in Shreya Ghoshal's ethereal voice, imagining the completeness that comes with finding a beloved.",
    moods: [{ S: 'Romantic' }, { S: 'Dreamy' }, { S: 'Longing' }, { S: 'Hopeful' }],
    filePath: path.join(__dirname, 'songs', 'Agar Tum Mil Jao_spotdown.org.m4a'),
  },
  {
    songId: 'song_013',
    name: 'Agar Tum Saath Ho',
    artist: 'Alka Yagnik, Arijit Singh',
    album: 'Loveholic Arijit Singh',
    description: 'A devastating duet about a relationship falling apart — two voices conveying the pain of emotional distance and silent goodbyes.',
    moods: [{ S: 'Heartbreak' }, { S: 'Sad' }, { S: 'Melancholic' }, { S: 'Emotional' }],
    filePath: path.join(__dirname, 'songs', 'Agar Tum Saath Ho (From _Tamasha_)_spotdown.org.m4a'),
  },
  {
    songId: 'song_014',
    name: 'Ai Raat Dheere Chal',
    artist: 'Anirudh Ravichander',
    album: '3 (Original Motion Picture Soundtrack)',
    description: 'A hauntingly atmospheric night song with poetic lyrics, asking the night to slow down as emotions run deep.',
    moods: [{ S: 'Melancholic' }, { S: 'Dreamy' }, { S: 'Calm' }, { S: 'Atmospheric' }],
    filePath: path.join(__dirname, 'songs', 'Ai Raat Dheere Chal - The Touch of Love_spotdown.org.m4a'),
  },
  {
    songId: 'song_015',
    name: 'Ainvayi Ainvayi',
    artist: 'Salim-Sulaiman, Sunidhi Chauhan',
    album: 'Band Baaja Baaraat',
    description: 'A bubbly, carefree track about flirtatious teasing and playful romance — breezy, fun, and irresistibly catchy.',
    moods: [{ S: 'Playful' }, { S: 'Fun' }, { S: 'Romantic' }, { S: 'Cheerful' }],
    filePath: path.join(__dirname, 'songs', 'Ainvayi Ainvayi_spotdown.org.m4a'),
  },
  {
    songId: 'song_016',
    name: 'Aisa Jadoo',
    artist: 'Sunidhi Chauhan',
    album: 'Khakee',
    description: "A soulful, mystical track about the magic of love, with Sunidhi's rich voice weaving a spell of warmth and enchantment.",
    moods: [{ S: 'Romantic' }, { S: 'Soulful' }, { S: 'Dreamy' }, { S: 'Warm' }],
    filePath: path.join(__dirname, 'songs', 'Aisa Jadoo_spotdown.org.m4a'),
  },
  {
    songId: 'song_017',
    name: 'Ajab Si',
    artist: 'Vishal-Shekhar, KK',
    album: 'Om Shanti Om',
    description: "A tender, innocent love song capturing the wonder of first love — KK's soft delivery evokes butterflies and wide-eyed romance.",
    moods: [{ S: 'Romantic' }, { S: 'Tender' }, { S: 'Dreamy' }, { S: 'Nostalgic' }],
    filePath: path.join(__dirname, 'songs', 'Ajab Si_spotdown.org.m4a'),
  },
  {
    songId: 'song_018',
    name: 'Angaaron (From "Pushpa")',
    artist: 'Shreya Ghoshal, Daler Mehndi',
    album: 'Angaaron (From "Pushpa")',
    description: 'A fierce, fiery track blazing with passion and attitude, matching the intensity of the Pushpa franchise with thunderous energy.',
    moods: [{ S: 'Fierce' }, { S: 'Energetic' }, { S: 'Bold' }, { S: 'Passionate' }],
    filePath: path.join(__dirname, 'songs', 'Angaaron (From _Pushpa 2 The Rule_) [HINDI]_spotdown.org.m4a'),
  },
  {
    songId: 'song_019',
    name: 'Arziyan',
    artist: 'Javed Ali, Kailash Kher',
    album: 'Delhi-6',
    description: 'A deeply spiritual and soulful Sufi prayer, layered with devotion and longing, offering a sense of peace and surrender.',
    moods: [{ S: 'Spiritual' }, { S: 'Peaceful' }, { S: 'Soulful' }, { S: 'Devotional' }],
    filePath: path.join(__dirname, 'songs', 'Arziyan_spotdown.org.m4a'),
  },
  {
    songId: 'song_020',
    name: 'Asal Mein',
    artist: 'Darshan Raval',
    album: 'Asal Mein',
    description: 'A heartfelt, introspective ballad about showing your true self in love, raw with sincerity and emotional depth.',
    moods: [{ S: 'Romantic' }, { S: 'Introspective' }, { S: 'Emotional' }, { S: 'Soulful' }],
    filePath: path.join(__dirname, 'songs', 'Asal Mein_spotdown.org.m4a'),
  },
  {
    songId: 'song_021',
    name: 'Baadal',
    artist: 'Vishal Dadlani, Sunidhi Chauhan',
    album: 'Akira',
    description: 'A powerful, rain-soaked anthem of resilience and defiance, with thunderous production and strong, empowering vocals.',
    moods: [{ S: 'Empowering' }, { S: 'Fierce' }, { S: 'Bold' }, { S: 'Energetic' }],
    filePath: path.join(__dirname, 'songs', 'Baadal_spotdown.org.m4a'),
  },
  // ── B ──────────────────────────────────────────────────────────────────────
  {
    songId: 'song_022',
    name: 'Baawre',
    artist: 'Mame Khan, Shankar-Ehsaan-Loy',
    album: 'Luck By Chance',
    description: 'A folk-tinged Rajasthani track infused with dreamy longing, evoking the madness of love through earthy, rustic melodies.',
    moods: [{ S: 'Dreamy' }, { S: 'Romantic' }, { S: 'Folk' }, { S: 'Nostalgic' }],
    filePath: path.join(__dirname, 'songs', 'Baawre_spotdown.org.m4a'),
  },
  {
    songId: 'song_023',
    name: 'Bahara',
    artist: 'Vishal-Shekhar, Shreya Ghoshal',
    album: 'I Hate Luv Storys',
    description: 'A blossoming spring love song — light, airy, and delicate, like the first petals of a romance unfurling with hope.',
    moods: [{ S: 'Romantic' }, { S: 'Hopeful' }, { S: 'Calm' }, { S: 'Cheerful' }],
    filePath: path.join(__dirname, 'songs', 'Bahara_spotdown.org.m4a'),
  },
  {
    songId: 'song_024',
    name: 'Balma',
    artist: 'Sreerama Chandra',
    album: 'Khiladi 786',
    description: 'A vibrant, flirtatious track brimming with mischievous energy and fun banter between lovers.',
    moods: [{ S: 'Playful' }, { S: 'Fun' }, { S: 'Romantic' }, { S: 'Energetic' }],
    filePath: path.join(__dirname, 'songs', 'Balma_spotdown.org.m4a'),
  },
  {
    songId: 'song_025',
    name: 'Barkha',
    artist: 'Sunidhi Chauhan',
    album: 'Unknown Album',
    description: 'A monsoon-drenched romantic track where rain becomes a metaphor for longing, love, and emotional release.',
    moods: [{ S: 'Romantic' }, { S: 'Melancholic' }, { S: 'Calm' }, { S: 'Dreamy' }],
    filePath: path.join(__dirname, 'songs', 'Barkha_spotdown.org.m4a'),
  },
  {
    songId: 'song_026',
    name: 'Be Intehaan',
    artist: 'Atif Aslam, Sunidhi Chauhan',
    album: 'Best of Romance: Atif Aslam',
    description: "A boundless love duet — Atif and Sunidhi's voices soar together in an epic declaration of limitless, all-consuming love.",
    moods: [{ S: 'Romantic' }, { S: 'Passionate' }, { S: 'Uplifting' }, { S: 'Hopeful' }],
    filePath: path.join(__dirname, 'songs', 'Be Intehaan_spotdown.org.m4a'),
  },
  {
    songId: 'song_027',
    name: 'Beedi (From "Omkara")',
    artist: 'Sunidhi Chauhan',
    album: 'Omkara',
    description: 'A bold, rustic item number with raw sensuality and folk flavour, crackling with uninhibited energy.',
    moods: [{ S: 'Bold' }, { S: 'Sensual' }, { S: 'Party' }, { S: 'Energetic' }],
    filePath: path.join(__dirname, 'songs', 'Beedi (From _Omkara_)_spotdown.org.m4a'),
  },
  {
    songId: 'song_028',
    name: 'Beete Lamhein',
    artist: 'KK, Mithoon',
    album: 'The Train',
    description: "A nostalgic, aching ballad about moments gone by — KK's voice lingers on memories with tender sorrow.",
    moods: [{ S: 'Nostalgic' }, { S: 'Melancholic' }, { S: 'Soulful' }, { S: 'Emotional' }],
    filePath: path.join(__dirname, 'songs', 'Beete Lamhein_spotdown.org.m4a'),
  },
  {
    songId: 'song_029',
    name: 'Bekhayali (Arijit Singh Version)',
    artist: 'Arijit Singh, Sachet Tandon',
    album: 'Bekhayali',
    description: "A haunting, existential ballad about losing oneself in despair — Arijit's raw, broken delivery makes heartbreak feel visceral.",
    moods: [{ S: 'Heartbreak' }, { S: 'Sad' }, { S: 'Intense' }, { S: 'Melancholic' }],
    filePath: path.join(__dirname, 'songs', 'Bekhayali (Arijit Singh Version) [From _Kabir Singh_]_spotdown.org.m4a'),
  },
  {
    songId: 'song_030',
    name: 'Bhage Re Mann',
    artist: 'Sunidhi Chauhan',
    album: 'Chameli',
    description: 'A restless, yearning track where the heart races towards something unknown — energetic with an undercurrent of longing.',
    moods: [{ S: 'Restless' }, { S: 'Longing' }, { S: 'Energetic' }, { S: 'Passionate' }],
    filePath: path.join(__dirname, 'songs', 'Bhage Re Mann_spotdown.org.m4a'),
  },
  {
    songId: 'song_031',
    name: 'Bhari Barsaat',
    artist: 'Mohit Bhardwaj',
    album: 'Bhari Barsaat',
    description: 'A lush monsoon ballad soaked in emotion, where rain and romance intertwine in melancholic beauty.',
    moods: [{ S: 'Melancholic' }, { S: 'Romantic' }, { S: 'Dreamy' }, { S: 'Calm' }],
    filePath: path.join(__dirname, 'songs', 'Bhari Barsaat_spotdown.org.m4a'),
  },
  {
    songId: 'song_032',
    name: 'Bijuria - Old Version',
    artist: 'Sonu Nigam',
    album: 'Mausam',
    description: "A timeless classic reimagined with Sonu Nigam's golden voice, steeped in seasonal romance and old-world charm.",
    moods: [{ S: 'Nostalgic' }, { S: 'Romantic' }, { S: 'Calm' }, { S: 'Soulful' }],
    filePath: path.join(__dirname, 'songs', 'Bijuria - Old Version_spotdown.org.m4a'),
  },
  {
    songId: 'song_033',
    name: 'Bin Tere',
    artist: 'Vishal-Shekhar, Shilpa Rao',
    album: 'I Hate Luv Storys',
    description: 'A quiet, aching song about incompleteness without a loved one — understated but deeply moving in its simplicity.',
    moods: [{ S: 'Longing' }, { S: 'Melancholic' }, { S: 'Romantic' }, { S: 'Calm' }],
    filePath: path.join(__dirname, 'songs', 'Bin Tere_spotdown.org.m4a'),
  },
  {
    songId: 'song_034',
    name: 'Bol Beliya',
    artist: 'Shankar-Ehsaan-Loy',
    album: 'Kill Dil',
    description: 'A quirky, foot-tapping number with an irresistible groove and carefree attitude that makes you want to move.',
    moods: [{ S: 'Fun' }, { S: 'Playful' }, { S: 'Energetic' }, { S: 'Cheerful' }],
    filePath: path.join(__dirname, 'songs', 'Bol Beliya_spotdown.org.m4a'),
  },
  {
    songId: 'song_035',
    name: 'Bol Na Halke Halke',
    artist: 'Shankar-Ehsaan-Loy',
    album: 'Jhoom Barabar Jhoom',
    description: 'A gentle, whispered romance — tender and intimate, like two people sharing secrets in hushed, loving tones.',
    moods: [{ S: 'Romantic' }, { S: 'Tender' }, { S: 'Calm' }, { S: 'Dreamy' }],
    filePath: path.join(__dirname, 'songs', 'Bol Na Halke Halke_spotdown.org.m4a'),
  },
  {
    songId: 'song_036',
    name: 'Bolna',
    artist: 'Tanishk Bagchi, Arijit Singh',
    album: 'Kapoor & Sons',
    description: "A deeply emotional plea for communication and connection in love, Arijit's raw sincerity makes every word feel urgent.",
    moods: [{ S: 'Emotional' }, { S: 'Romantic' }, { S: 'Intense' }, { S: 'Longing' }],
    filePath: path.join(__dirname, 'songs', 'Bolna_spotdown.org.m4a'),
  },
  {
    songId: 'song_037',
    name: 'Bulleya - Reprise',
    artist: 'Pritam, Arijit Singh',
    album: 'Ae Dil Hai Mushkil',
    description: 'A stripped-back, meditative Sufi reprise full of restless devotion and the agony of love beyond reason.',
    moods: [{ S: 'Spiritual' }, { S: 'Melancholic' }, { S: 'Introspective' }, { S: 'Soulful' }],
    filePath: path.join(__dirname, 'songs', 'Bulleya - Reprise_spotdown.org.m4a'),
  },
  // ── C ──────────────────────────────────────────────────────────────────────
  {
    songId: 'song_038',
    name: 'Chaahat',
    artist: 'Prismin',
    album: 'Chaahat',
    description: 'A modern, soulful track about deep desire and longing, blending contemporary production with heartfelt emotion.',
    moods: [{ S: 'Romantic' }, { S: 'Longing' }, { S: 'Soulful' }, { S: 'Dreamy' }],
    filePath: path.join(__dirname, 'songs', 'Chaahat_spotdown.org.m4a'),
  },
  {
    songId: 'song_039',
    name: 'Chahun Main Ya Naa',
    artist: 'Palak Muchhal, Arijit Singh',
    album: 'Aashiqui 2',
    description: 'A bittersweet love confession caught between desire and fear — a delicate emotional tightrope captured beautifully by both vocalists.',
    moods: [{ S: 'Romantic' }, { S: 'Emotional' }, { S: 'Bittersweet' }, { S: 'Tender' }],
    filePath: path.join(__dirname, 'songs', 'Chahun Main Ya Naa (From _Aashiqui 2_)_spotdown.org.m4a'),
  },
  {
    songId: 'song_040',
    name: 'Chal Ghar Chalen',
    artist: 'Mithoon, Arijit Singh',
    album: 'Malang',
    description: "A deeply intimate song about finding home in a person — Arijit's voice carries an overwhelming sense of belonging and love.",
    moods: [{ S: 'Romantic' }, { S: 'Emotional' }, { S: 'Warm' }, { S: 'Soulful' }],
    filePath: path.join(__dirname, 'songs', 'Chal Ghar Chalen (From _Malang - Unleash The Madness_) [Mithoon feat. Arijit Singh]_spotdown.org.m4a'),
  },
  {
    songId: 'song_041',
    name: 'Chal Wahan Jaate Hain',
    artist: 'Arijit Singh, Rashmi Singh',
    album: 'Chal Wahan Jaate Hain',
    description: 'A sweeping romantic track full of wanderlust and deep love — an invitation to escape together into a world of just the two of you.',
    moods: [{ S: 'Romantic' }, { S: 'Dreamy' }, { S: 'Hopeful' }, { S: 'Warm' }],
    filePath: path.join(__dirname, 'songs', 'Chal Wahan Jaate Hain_spotdown.org.m4a'),
  },
  {
    songId: 'song_042',
    name: 'Chandaniya - Lori Lori',
    artist: 'Sajid-Wajid, Shreya Ghoshal',
    album: 'Rowdy Rathore',
    description: 'A soothing, moonlit lullaby-inspired track that wraps you in warmth, nostalgia, and gentle tender love.',
    moods: [{ S: 'Calm' }, { S: 'Warm' }, { S: 'Nostalgic' }, { S: 'Dreamy' }],
    filePath: path.join(__dirname, 'songs', 'Chandaniya - Lori Lori_spotdown.org.m4a'),
  },
  {
    songId: 'song_043',
    name: 'Channa Mereya',
    artist: 'Pritam, Arijit Singh',
    album: 'Ae Dil Hai Mushkil',
    description: 'One of the most iconic heartbreak songs of its era — a beautifully mournful farewell that finds peace and love even in letting go.',
    moods: [{ S: 'Heartbreak' }, { S: 'Melancholic' }, { S: 'Soulful' }, { S: 'Bittersweet' }],
    filePath: path.join(__dirname, 'songs', 'Channa Mereya_spotdown.org.m4a'),
  },
  {
    songId: 'song_044',
    name: 'Chhaliya',
    artist: 'Vishal-Shekhar, Sunidhi Chauhan',
    album: 'Tashan',
    description: "A cheeky, flirtatious track with a punchy beat and mischievous energy that's impossible not to groove to.",
    moods: [{ S: 'Playful' }, { S: 'Fun' }, { S: 'Energetic' }, { S: 'Bold' }],
    filePath: path.join(__dirname, 'songs', 'Chhaliya_spotdown.org.m4a'),
  },
  {
    songId: 'song_045',
    name: 'Chhod Diya',
    artist: 'Arijit Singh',
    album: 'Baazaar',
    description: 'A quiet devastation — Arijit Singh strips heartbreak down to its bones in this achingly restrained ballad about abandonment.',
    moods: [{ S: 'Heartbreak' }, { S: 'Sad' }, { S: 'Melancholic' }, { S: 'Quiet' }],
    filePath: path.join(__dirname, 'songs', 'Chhod Diya_spotdown.org.m4a'),
  },
  {
    songId: 'song_046',
    name: 'Chikni Chameli',
    artist: 'Ajay-Atul, Shreya Ghoshal',
    album: 'Agneepath',
    description: 'A fiery, high-octane item number bursting with attitude, colour, and unstoppable feminine energy.',
    moods: [{ S: 'Bold' }, { S: 'Energetic' }, { S: 'Party' }, { S: 'Sensual' }],
    filePath: path.join(__dirname, 'songs', 'Chikni Chameli_spotdown.org.m4a'),
  },
  {
    songId: 'song_047',
    name: 'Chogada',
    artist: 'Darshan Raval, Asees Kaur',
    album: 'Loveyatri',
    description: 'A lively, colourful Navratri garba celebration — irresistibly festive with joyous energy and folk-infused beats.',
    moods: [{ S: 'Festive' }, { S: 'Joyful' }, { S: 'Energetic' }, { S: 'Celebratory' }],
    filePath: path.join(__dirname, 'songs', 'Chogada (From _Loveyatri_)_spotdown.org.m4a'),
  },
  {
    songId: 'song_048',
    name: 'Chor Bazaari',
    artist: 'Pritam, Neeraj Shridhar',
    album: 'Love Aaj Kal',
    description: 'A carefree, quirky track about the unpredictable theft of the heart — fun, punchy, and full of romantic mischief.',
    moods: [{ S: 'Playful' }, { S: 'Fun' }, { S: 'Romantic' }, { S: 'Carefree' }],
    filePath: path.join(__dirname, 'songs', 'Chor Bazaari_spotdown.org.m4a'),
  },
  {
    songId: 'song_049',
    name: 'Chor Bazari Phir Se',
    artist: 'Pritam, Tanishk Bagchi',
    album: 'Love Aaj Kal 2',
    description: 'A contemporary reimagining of a beloved track, updated with fresh energy while retaining its charming romantic playfulness.',
    moods: [{ S: 'Playful' }, { S: 'Fun' }, { S: 'Romantic' }, { S: 'Energetic' }],
    filePath: path.join(__dirname, 'songs', 'Chor Bazari Phir Se (From _Bhool Chuk Maaf_)_spotdown.org.m4a'),
  },
  {
    songId: 'song_050',
    name: 'Chup Chup Ke',
    artist: 'Shankar-Ehsaan-Loy',
    album: 'Bunty Aur Babli',
    description: 'A tongue-in-cheek, sneaky love track full of quiet mischief and whispered romance with a bouncy, fun rhythm.',
    moods: [{ S: 'Playful' }, { S: 'Fun' }, { S: 'Romantic' }, { S: 'Carefree' }],
    filePath: path.join(__dirname, 'songs', 'Chup Chup Ke_spotdown.org.m4a'),
  },
  {
    songId: 'song_051',
    name: 'Chura Liya',
    artist: 'Sanam',
    album: 'Unknown Album',
    description: 'A breezy, nostalgic reimagining of a classic Bollywood hit — light-hearted, romantic, and timelessly charming.',
    moods: [{ S: 'Romantic' }, { S: 'Nostalgic' }, { S: 'Cheerful' }, { S: 'Calm' }],
    filePath: path.join(__dirname, 'songs', 'Chura Liya_spotdown.org.m4a'),
  },
  {
    songId: 'song_052',
    name: 'Crazy Kiya Re',
    artist: 'Pritam, Sunidhi Chauhan',
    album: 'Dhoom:2',
    description: 'An electrifying, daring track that crackles with wild, rebellious energy — as bold and exhilarating as the film it belongs to.',
    moods: [{ S: 'Energetic' }, { S: 'Bold' }, { S: 'Fierce' }, { S: 'Party' }],
    filePath: path.join(__dirname, 'songs', 'Crazy Kiya Re_spotdown.org.m4a'),
  },
  // ── D ──────────────────────────────────────────────────────────────────────
  {
    songId: 'song_053',
    name: 'Dance Pe Chance',
    artist: 'Salim-Sulaiman, Sunidhi Chauhan',
    album: 'Rab Ne Bana Di Jodi',
    description: 'An irresistibly fun dance track that pulls you onto the floor — joyful, vibrant, and impossible to sit still to.',
    moods: [{ S: 'Fun' }, { S: 'Energetic' }, { S: 'Party' }, { S: 'Joyful' }],
    filePath: path.join(__dirname, 'songs', 'Dance Pe Chance_spotdown.org.m4a'),
  },
  {
    songId: 'song_054',
    name: 'Darkhaast',
    artist: 'Mithoon, Arijit Singh',
    album: 'Shivaay',
    description: "An earnest, heartfelt request for love — Arijit's voice carries a quiet, desperate sincerity over Mithoon's brooding production.",
    moods: [{ S: 'Romantic' }, { S: 'Emotional' }, { S: 'Longing' }, { S: 'Intense' }],
    filePath: path.join(__dirname, 'songs', 'Darkhaast_spotdown.org.m4a'),
  },
  {
    songId: 'song_055',
    name: 'Deadly Zone',
    artist: 'Dhanda Nyoliwala',
    album: 'Deadly Zone',
    description: 'A hard-hitting, aggressive track dripping with street swagger and fearless attitude.',
    moods: [{ S: 'Fierce' }, { S: 'Bold' }, { S: 'Energetic' }, { S: 'Confident' }],
    filePath: path.join(__dirname, 'songs', 'Deadly Zone_spotdown.org.m4a'),
  },
  {
    songId: 'song_056',
    name: 'Deewana Hai Dekho',
    artist: 'Sandesh Shandilya',
    album: 'Kabhi Khushi Kabhie Gham',
    description: 'A joyful, over-the-top celebration of being madly in love — exuberant, colourful, and utterly carefree.',
    moods: [{ S: 'Joyful' }, { S: 'Fun' }, { S: 'Romantic' }, { S: 'Energetic' }],
    filePath: path.join(__dirname, 'songs', 'Deewana Hai Dekho_spotdown.org.m4a'),
  },
  {
    songId: 'song_057',
    name: 'Deewana Kar Raha Hai',
    artist: 'Javed Ali',
    album: 'Raaz 3',
    description: "A thrilling, obsessive love song with an eerie undertone — Javed Ali's passionate voice captures maddening, all-consuming desire.",
    moods: [{ S: 'Passionate' }, { S: 'Intense' }, { S: 'Romantic' }, { S: 'Longing' }],
    filePath: path.join(__dirname, 'songs', 'Deewana Kar Raha Hai_spotdown.org.m4a'),
  },
  {
    songId: 'song_058',
    name: 'Dekh Lena',
    artist: 'Arijit Singh, Tulsi Kumar',
    album: 'Tum Bin 2',
    description: 'A gentle, reassuring love promise — two voices weave a warm, hopeful narrative of togetherness and unwavering support.',
    moods: [{ S: 'Romantic' }, { S: 'Warm' }, { S: 'Hopeful' }, { S: 'Tender' }],
    filePath: path.join(__dirname, 'songs', 'Dekh Lena (From _Tum Bin 2_)_spotdown.org'),
  },
  {
    songId: 'song_059',
    name: 'Der Lagi Lekin',
    artist: 'Shankar Mahadevan',
    album: 'Zindagi Na Milegi Dobara',
    description: 'A triumphant, emotionally soaring track about being late but finally finding love — hopeful and profoundly moving.',
    moods: [{ S: 'Hopeful' }, { S: 'Uplifting' }, { S: 'Emotional' }, { S: 'Romantic' }],
    filePath: path.join(__dirname, 'songs', 'Der Lagi Lekin_spotdown.org.m4a'),
  },
  {
    songId: 'song_060',
    name: 'Desi Girl',
    artist: 'Vishal-Shekhar, Shankar Mahadevan',
    album: 'Dostana',
    description: 'A vibrant, pride-filled celebration of the desi girl — fun, colourful, and radiating confident charm.',
    moods: [{ S: 'Fun' }, { S: 'Confident' }, { S: 'Energetic' }, { S: 'Cheerful' }],
    filePath: path.join(__dirname, 'songs', 'Desi Girl_spotdown.org.m4a'),
  },
  {
    songId: 'song_061',
    name: 'Desi Kali',
    artist: 'Pritam, Neeraj Shridhar',
    album: 'Golmaal 3',
    description: 'A lively, playful track with rustic desi flavour and infectious energy that brings out the joy of village celebrations.',
    moods: [{ S: 'Playful' }, { S: 'Fun' }, { S: 'Festive' }, { S: 'Cheerful' }],
    filePath: path.join(__dirname, 'songs', 'Desi Kali_spotdown.org.m4a'),
  },
  {
    songId: 'song_062',
    name: 'Dhadak - Title Track',
    artist: 'Ajay Gogavale, Shreya Ghoshal',
    album: 'Dhadak',
    description: 'A racing heartbeat of young love — pure, urgent, and beautifully earnest in its portrayal of new, breathless romance.',
    moods: [{ S: 'Romantic' }, { S: 'Hopeful' }, { S: 'Tender' }, { S: 'Energetic' }],
    filePath: path.join(__dirname, 'songs', 'Dhadak - Title Track_spotdown.org.m4a'),
  },
  {
    songId: 'song_063',
    name: 'Dhadak Dhadak',
    artist: 'Shankar-Ehsaan-Loy',
    album: 'Bunty Aur Babli',
    description: 'A pounding, exhilarating track capturing the rhythm of an adventurous heart in love — fun, fast, and full of life.',
    moods: [{ S: 'Energetic' }, { S: 'Fun' }, { S: 'Romantic' }, { S: 'Uplifting' }],
    filePath: path.join(__dirname, 'songs', 'Dhadak Dhadak_spotdown.org.m4a'),
  },
  {
  songId: 'song_064',
  name: 'Dhurandhar - Title Track',
  artist: 'Shashwat Sachdev, Hanumankind, Jasmine Sandlas, Sudhir Yaduvanshi, Charanjit Ahuja, Muhammad Sadiq',
  album: 'Dhurandhar',
  description: 'A powerful title track with intense energy and strong vocals.',
  moods: [{ S: 'Energetic' }, { S: 'Intense' }, { S: 'Powerful' }, { S: 'Motivational' }],
  filePath: path.join(__dirname, 'songs', 'Dhurandhar - Title Track_spotdown.org.m4a'),
},
{
  songId: 'song_065',
  name: 'Dil Chahta Hai (Reprise)',
  artist: 'Shankar Mahadevan',
  album: 'Dil Chahta Hai',
  description: 'A nostalgic reprise celebrating friendship and youth.',
  moods: [{ S: 'Nostalgic' }, { S: 'Happy' }, { S: 'Friendship' }, { S: 'Feel Good' }],
  filePath: path.join(__dirname, 'songs', 'Dil Chahta Hai(Reprise)_spotdown.org.m4a'),
},
{
  songId: 'song_066',
  name: 'Dil Chahta Hai',
  artist: 'Shankar Mahadevan',
  album: 'Dil Chahta Hai',
  description: 'A timeless friendship anthem about living life freely.',
  moods: [{ S: 'Happy' }, { S: 'Friendship' }, { S: 'Freedom' }, { S: 'Feel Good' }],
  filePath: path.join(__dirname, 'songs', 'Dil Chahta Hai_spotdown.org.m4a'),
},
{
  songId: 'song_067',
  name: 'Dil Cheez Tujhe Dedi',
  artist: 'Ankit Tiwari, Arijit Singh',
  album: 'Airlift',
  description: 'A passionate romantic song expressing deep love.',
  moods: [{ S: 'Romantic' }, { S: 'Passionate' }, { S: 'Emotional' }, { S: 'Love' }],
  filePath: path.join(__dirname, 'songs', 'Dil Cheez Tujhe Dedi_spotdown.org.m4a'),
},
{
  songId: 'song_068',
  name: 'Dil Dhadakne Do',
  artist: 'Joi Barua, Suraj Jagan',
  album: 'Zindagi Na Milegi Dobara',
  description: 'A liberating song about living freely and following your heart.',
  moods: [{ S: 'Motivational' }, { S: 'Happy' }, { S: 'Freedom' }, { S: 'Uplifting' }],
  filePath: path.join(__dirname, 'songs', 'Dil Dhadakne Do_spotdown.org.m4a'),
},
{
  songId: 'song_069',
  name: 'Dil Diyan Gallan',
  artist: 'Atif Aslam',
  album: 'YRF Top 10 - Falling in Love',
  description: 'A soft romantic ballad about deep love and connection.',
  moods: [{ S: 'Romantic' }, { S: 'Soft' }, { S: 'Love' }, { S: 'Calm' }],
  filePath: path.join(__dirname, 'songs', 'Dil Diyan Gallan_spotdown.org.m4a'),
},
{
  songId: 'song_070',
  name: 'Dil Ibaadat',
  artist: 'Pritam, KK, Sayeed Quadri',
  album: 'Tum Mile (Original Motion Picture Soundtrack)',
  description: 'A deeply emotional love song full of longing and devotion.',
  moods: [{ S: 'Romantic' }, { S: 'Emotional' }, { S: 'Soulful' }, { S: 'Melancholic' }],
  filePath: path.join(__dirname, 'songs', 'Dil Ibaadat_spotdown.org.m4a'),
},
{
  songId: 'song_071',
  name: 'Dil Ke Paas (Indian Version)',
  artist: 'Arijit Singh, Abhijit Vaghani, Kalyanji-Anandji',
  album: 'Dil Ke Paas (Indian Version)',
  description: 'A romantic recreation of a classic love song.',
  moods: [{ S: 'Romantic' }, { S: 'Nostalgic' }, { S: 'Love' }, { S: 'Emotional' }],
  filePath: path.join(__dirname, 'songs', 'Dil Ke Paas (Indian Version)_spotdown.org.m4a'),
},
{
  songId: 'song_072',
  name: 'Dil Ke Paas',
  artist: 'Arijit Singh, Tulsi Kumar, Neuman Pinto',
  album: 'Wajah Tum Ho',
  description: 'A soft romantic song about closeness and love.',
  moods: [{ S: 'Romantic' }, { S: 'Love' }, { S: 'Soft' }, { S: 'Emotional' }],
  filePath: path.join(__dirname, 'songs', 'Dil Ke Paas_spotdown.org.m4a'),
},
{
  songId: 'song_073',
  name: 'Dil Kyun Yeh Mera',
  artist: 'KK',
  album: 'Kites',
  description: 'A soft romantic song about falling deeply in love.',
  moods: [{ S: 'Romantic' }, { S: 'Dreamy' }, { S: 'Calm' }, { S: 'Emotional' }],
  filePath: path.join(__dirname, 'songs', 'Dil Kyun Yeh Mera_spotdown.org.m4a'),
},
{
  songId: 'song_074',
  name: 'Dil Royi Jaye',
  artist: 'Arijit Singh',
  album: 'De De Pyaar De',
  description: 'A sad romantic song about heartbreak and separation.',
  moods: [{ S: 'Sad' }, { S: 'Heartbreak' }, { S: 'Emotional' }, { S: 'Melancholic' }],
  filePath: path.join(__dirname, 'songs', 'Dil Royi Jaye_spotdown.org.m4a'),
},
{
  songId: 'song_075',
  name: 'Dil Se Re',
  artist: 'A.R. Rahman, Anuradha Sriram, Anupama',
  album: 'Dil Se (Original Motion Picture Soundtrack)',
  description: 'An intense song about passionate love and obsession.',
  moods: [{ S: 'Intense' }, { S: 'Passionate' }, { S: 'Emotional' }, { S: 'Love' }],
  filePath: path.join(__dirname, 'songs', 'Dil Se Re_spotdown.org.m4a'),
},
{
  songId: 'song_076',
  name: 'Dilliwali Girlfriend',
  artist: 'Pritam, Arijit Singh, Sunidhi Chauhan',
  album: 'Yeh Jawaani Hai Deewani',
  description: 'A fun party song with energetic beats.',
  moods: [{ S: 'Party' }, { S: 'Fun' }, { S: 'Energetic' }, { S: 'Happy' }],
  filePath: path.join(__dirname, 'songs', 'Dilliwaali Girlfriend_spotdown.org.m4a'),
},
{
  songId: 'song_077',
  name: 'Dilnashin Dilnashin',
  artist: 'KK',
  album: 'Aashiq Banaya Aapne',
  description: 'A romantic song with a soft emotional vibe.',
  moods: [{ S: 'Romantic' }, { S: 'Love' }, { S: 'Emotional' }, { S: 'Soft' }],
  filePath: path.join(__dirname, 'songs', 'Dilnashin Dilnashin_spotdown.org.m4a'),
},
{
  songId: 'song_078',
  name: 'Dola Re Dola',
  artist: 'Kavita Krishnamurthy, Shreya Ghoshal, KK',
  album: 'Devdas (Original Motion Picture Soundtrack)',
  description: 'A grand classical dance song from Devdas.',
  moods: [{ S: 'Classical' }, { S: 'Dance' }, { S: 'Grand' }, { S: 'Dramatic' }],
  filePath: path.join(__dirname, 'songs', 'Dola Re Dola - From _Devdas__spotdown.org.m4a'),
},
{
  songId: 'song_079',
  name: 'Doli Uthli',
  artist: 'Naaz Aulakh',
  album: 'Unknown Album',
  description: 'A Punjabi emotional track.',
  moods: [{ S: 'Punjabi' }, { S: 'Emotional' }, { S: 'Sad' }, { S: 'Folk' }],
  filePath: path.join(__dirname, 'songs', 'DOLI UTHLI_spotdown.org.m4a'),
},
{
  songId: 'song_080',
  name: 'Dooriyan',
  artist: 'Pritam, Mohit Chauhan',
  album: 'Love Aaj Kal (Original Motion Picture Soundtrack)',
  description: 'A song about distance and love.',
  moods: [{ S: 'Sad' }, { S: 'Romantic' }, { S: 'Emotional' }, { S: 'Longing' }],
  filePath: path.join(__dirname, 'songs', 'Dooriyan_spotdown.org.m4a'),
},
{
  songId: 'song_081',
  name: 'Dracula - JENNIE Remix',
  artist: 'Tame Impala, JENNIE',
  album: 'Dracula (Remix)',
  description: 'A remix track with dark pop vibes.',
  moods: [{ S: 'Pop' }, { S: 'Dark' }, { S: 'Chill' }, { S: 'Remix' }],
  filePath: path.join(__dirname, 'songs', 'Dracula - JENNIE Remix_spotdown.org.m4a'),
},
{
  songId: 'song_082',
  name: 'Dua Karo',
  artist: 'Sachin-Jigar, Arijit Singh, Bohemia',
  album: 'Street Dancer 3D',
  description: 'An emotional prayer-like song.',
  moods: [{ S: 'Emotional' }, { S: 'Motivational' }, { S: 'Sad' }, { S: 'Hopeful' }],
  filePath: path.join(__dirname, 'songs', 'Dua Karo (From _Street Dancer 3D_)_spotdown.org.m4a'),
},
{
  songId: 'song_083',
  name: 'Duaa',
  artist: 'Nandini Srikar, Arijit Singh',
  album: 'Arijit Singh Broken Strings',
  description: 'A soulful emotional song.',
  moods: [{ S: 'Emotional' }, { S: 'Sad' }, { S: 'Soulful' }, { S: 'Melancholic' }],
  filePath: path.join(__dirname, 'songs', 'Duaa (From _Shanghai_)_spotdown.org.m4a'),
},
{
  songId: 'song_084',
  name: 'Ek Din Teri Raahon Mein',
  artist: 'Javed Ali, Pritam',
  album: 'Naqaab (Original Motion Picture Soundtrack)',
  description: 'A soft romantic melody.',
  moods: [{ S: 'Romantic' }, { S: 'Calm' }, { S: 'Love' }, { S: 'Emotional' }],
  filePath: path.join(__dirname, 'songs', 'Ek Din Teri Raahon_spotdown.org.m4a'),
},
{
  songId: 'song_085',
  name: 'Ek Ladki Ko Dekha Toh Aisa Laga',
  artist: 'Darshan Raval, Rochak Kohli',
  album: 'Ek Ladki Ko Dekha Toh Aisa Laga',
  description: 'A romantic admiration song.',
  moods: [{ S: 'Romantic' }, { S: 'Happy' }, { S: 'Love' }, { S: 'Soft' }],
  filePath: path.join(__dirname, 'songs', 'Ek Ladki Ko Dekha Toh Aisa Laga_spotdown.org.m4a'),
},
{
  songId: 'song_086',
  name: 'Ek Meetha Marz De Ke',
  artist: 'Mohit Chauhan, Madhushree',
  album: 'Welcome To Sajjanpur',
  description: 'A soft romantic melody.',
  moods: [{ S: 'Romantic' }, { S: 'Soft' }, { S: 'Love' }, { S: 'Calm' }],
  filePath: path.join(__dirname, 'songs', 'Ek Meetha Marz De Ke_spotdown.org.m4a'),
},
{
  songId: 'song_087',
  name: 'Espresso',
  artist: 'Sabrina Carpenter',
  album: 'Espresso',
  description: 'A modern pop track with upbeat vibes.',
  moods: [{ S: 'Pop' }, { S: 'Happy' }, { S: 'Energetic' }, { S: 'Fun' }],
  filePath: path.join(__dirname, 'songs', 'Espresso_spotdown.org.m4a'),
},
{
  songId: 'song_088',
  name: 'Feel My Love',
  artist: 'KK',
  album: 'Arya',
  description: 'A romantic emotional song.',
  moods: [{ S: 'Romantic' }, { S: 'Emotional' }, { S: 'Love' }, { S: 'Soft' }],
  filePath: path.join(__dirname, 'songs', 'Feel My Love_spotdown.org.m4a'),
},
{
  songId: 'song_089',
  name: 'Gallan Goodiyaan',
  artist: 'Yashita Sharma, Manish Kumar Tipu, Farhan Akhtar, Shankar Mahadevan, Sukhwinder Singh',
  album: 'Dil Dhadakne Do',
  description: 'A lively celebration song.',
  moods: [{ S: 'Happy' }, { S: 'Party' }, { S: 'Celebration' }, { S: 'Fun' }],
  filePath: path.join(__dirname, 'songs', 'Gallan Goodiyaan_spotdown.org.m4a'),
},
{
  songId: 'song_090',
  name: 'Gazab',
  artist: 'Sunidhi Chauhan, Shaan, Pritam',
  album: 'Aa Dekhen Zara',
  description: 'A fun energetic Bollywood track.',
  moods: [{ S: 'Fun' }, { S: 'Energetic' }, { S: 'Party' }, { S: 'Happy' }],
  filePath: path.join(__dirname, 'songs', 'Gazab_spotdown.org.m4a'),
},
{
  songId: 'song_091',
  name: 'Ghungroo',
  artist: 'Vishal-Shekhar, Arijit Singh, Shilpa Rao, Kumaar',
  album: 'War',
  description: 'A stylish dance track.',
  moods: [{ S: 'Party' }, { S: 'Dance' }, { S: 'Energetic' }, { S: 'Fun' }],
  filePath: path.join(__dirname, 'songs', 'Ghungroo (From _War_)_spotdown.org.m4a'),
},
{
  songId: 'song_092',
  name: 'Gulabi Aankhen',
  artist: 'Sanam',
  album: 'Universally SANAM',
  description: 'A recreated romantic classic with soft modern vibes.',
  moods: [{ S: 'Romantic' }, { S: 'Soft' }, { S: 'Love' }, { S: 'Nostalgic' }],
  filePath: path.join(__dirname, 'songs', 'Gulabi Aankhen_spotdown.org.m4a'),
},
{
  songId: 'song_093',
  name: 'Guli Mata',
  artist: 'Saad Lamjarred, Shreya Ghoshal, Rajat Nagpal',
  album: 'Guli Mata',
  description: 'A global pop romantic track.',
  moods: [{ S: 'Romantic' }, { S: 'Pop' }, { S: 'Love' }, { S: 'Chill' }],
  filePath: path.join(__dirname, 'songs', 'Guli Mata_spotdown.org.m4a'),
},
{
  songId: 'song_094',
  name: 'Guzarish',
  artist: 'Javed Ali',
  album: 'Ghajini',
  description: 'A deeply emotional and soulful song.',
  moods: [{ S: 'Emotional' }, { S: 'Soulful' }, { S: 'Sad' }, { S: 'Romantic' }],
  filePath: path.join(__dirname, 'songs', 'Guzarish_spotdown.org.m4a'),
},
{
  songId: 'song_095',
  name: 'Haan Main Galat',
  artist: 'Pritam, Arijit Singh, Shashwat Singh',
  album: 'Love Aaj Kal',
  description: 'A modern upbeat love song.',
  moods: [{ S: 'Happy' }, { S: 'Romantic' }, { S: 'Fun' }, { S: 'Energetic' }],
  filePath: path.join(__dirname, 'songs', 'Haan Main Galat (From _Love Aaj Kal_)_spotdown.org.m4a'),
},
{
  songId: 'song_096',
  name: 'Haan Tu Hain',
  artist: 'Pritam, KK, Sayeed Quadri',
  album: 'Jannat (Original Motion Picture Soundtrack)',
  description: 'A soulful romantic song.',
  moods: [{ S: 'Romantic' }, { S: 'Emotional' }, { S: 'Love' }, { S: 'Soulful' }],
  filePath: path.join(__dirname, 'songs', 'Haan Tu Hain_spotdown.org.m4a'),
},
{
  songId: 'song_097',
  name: 'Hadippa The Remix',
  artist: 'Pritam, Mika Singh, Sunidhi Chauhan',
  album: 'Dil Bole Hadippa',
  description: 'An energetic remix dance track.',
  moods: [{ S: 'Dance' }, { S: 'Party' }, { S: 'Energetic' }, { S: 'Fun' }],
  filePath: path.join(__dirname, 'songs', 'Hadippa The Remix_spotdown.org.m4a'),
},
{
  songId: 'song_098',
  name: 'Hai Dil Ye Mera',
  artist: 'Arijit Singh',
  album: 'Hate Story 2',
  description: 'A soft romantic emotional track.',
  moods: [{ S: 'Romantic' }, { S: 'Emotional' }, { S: 'Love' }, { S: 'Sad' }],
  filePath: path.join(__dirname, 'songs', 'Hai Dil Ye Mera_spotdown.org.m4a'),
},
{
  songId: 'song_099',
  name: 'Halka Halka',
  artist: 'Sunidhi Chauhan, Divya Kumar, Amit Trivedi',
  album: 'Fanne Khan',
  description: 'A romantic soft melody.',
  moods: [{ S: 'Romantic' }, { S: 'Soft' }, { S: 'Love' }, { S: 'Calm' }],
  filePath: path.join(__dirname, 'songs', 'Halka Halka (From _Fanne Khan_)_spotdown.org.m4a'),
},
{
  songId: 'song_100',
  name: 'Halkat Jawani',
  artist: 'Salim-Sulaiman, Sunidhi Chauhan',
  album: 'Heroine',
  description: 'A bold dance track.',
  moods: [{ S: 'Dance' }, { S: 'Bold' }, { S: 'Party' }, { S: 'Energetic' }],
  filePath: path.join(__dirname, 'songs', 'Halkat Jawani_spotdown.org.m4a'),
},
{
  songId: 'song_101',
  name: 'Hamari Adhuri Kahani (Title Track)',
  artist: 'Jeet Gannguli, Arijit Singh, Rashmi Virag',
  album: 'Hamari Adhuri Kahani',
  description: 'A very emotional love song.',
  moods: [{ S: 'Emotional' }, { S: 'Sad' }, { S: 'Romantic' }, { S: 'Soulful' }],
  filePath: path.join(__dirname, 'songs', 'Hamari Adhuri Kahani (Title Track)_spotdown.org.m4a'),
},
{
  songId: 'song_102',
  name: 'Hazaar Baar',
  artist: 'Arijit Singh, Shreya Ghoshal, Thaman S, Irshad Kamil',
  album: 'Baby John',
  description: 'A romantic duet.',
  moods: [{ S: 'Romantic' }, { S: 'Love' }, { S: 'Emotional' }, { S: 'Soft' }],
  filePath: path.join(__dirname, 'songs', 'Hazaar Baar - From _Baby John__spotdown.org.m4a'),
},
{
  songId: 'song_103',
  name: 'Hey Shona',
  artist: 'Vishal-Shekhar, Shaan, Sunidhi Chauhan, Javed Akhtar',
  album: 'Ta Ra Rum Pum',
  description: 'A cute romantic song.',
  moods: [{ S: 'Romantic' }, { S: 'Cute' }, { S: 'Love' }, { S: 'Happy' }],
  filePath: path.join(__dirname, 'songs', 'Hey Shona_spotdown.org.m4a'),
},
{
  songId: 'song_104',
  name: 'Heyy Babyy',
  artist: 'Neeraj Shridhar, Raman, Pervez Qadir, Loy Mendonsa, Shankar Mahadevan, Sameer Anjaan',
  album: 'Heyy Babyy',
  description: 'A fun Bollywood title track.',
  moods: [{ S: 'Fun' }, { S: 'Happy' }, { S: 'Party' }, { S: 'Energetic' }],
  filePath: path.join(__dirname, 'songs', 'Heyy Babyy_spotdown.org.m4a'),
},
{
  songId: 'song_105',
  name: 'Hindustani',
  artist: 'Shankar Mahadevan, Udit Narayan, Mahalaxmi Iyer, Dominique',
  album: 'Dus',
  description: 'A patriotic and energetic song.',
  moods: [{ S: 'Patriotic' }, { S: 'Energetic' }, { S: 'Motivational' }, { S: 'Powerful' }],
  filePath: path.join(__dirname, 'songs', 'Hindustani (Suno Gaur Se Duniya Walo)_spotdown.org.m4a'),
},
{
  songId: 'song_106',
  name: 'I Am In Love',
  artist: 'Pritam, KK, Dominique, Neelesh Misra',
  album: 'Once Upon A Time In Mumbaai',
  description: 'A soft romantic song.',
  moods: [{ S: 'Romantic' }, { S: 'Soft' }, { S: 'Love' }, { S: 'Emotional' }],
  filePath: path.join(__dirname, 'songs', 'I Am In Love_spotdown.org.m4a'),
},
{
  songId: 'song_107',
  name: 'Ik Junoon (Paint It Red)',
  artist: 'Vishal Dadlani',
  album: 'Zindagi Na Milegi Dobara',
  description: 'An energetic travel and adventure song.',
  moods: [{ S: 'Energetic' }, { S: 'Adventure' }, { S: 'Motivational' }, { S: 'Travel' }],
  filePath: path.join(__dirname, 'songs', 'Ik Junoon (Paint It Red)_spotdown.org.m4a'),
},
{
  songId: 'song_108',
  name: 'Ilahi',
  artist: 'Pritam, Arijit Singh',
  album: 'Yeh Jawaani Hai Deewani',
  description: 'A travel and freedom song.',
  moods: [{ S: 'Travel' }, { S: 'Freedom' }, { S: 'Happy' }, { S: 'Motivational' }],
  filePath: path.join(__dirname, 'songs', 'Ilahi_spotdown.org.m4a'),
},
{
  songId: 'song_109',
  name: 'Intezaar Hai',
  artist: 'Anirudh Ravichander',
  album: 'Unknown Album',
  description: 'A calm emotional waiting song.',
  moods: [{ S: 'Emotional' }, { S: 'Calm' }, { S: 'Sad' }, { S: 'Love' }],
  filePath: path.join(__dirname, 'songs', 'Intezaar Hai_spotdown.org.m4a'),
},
{
  songId: 'song_110',
  name: 'Intezaar',
  artist: 'Arijit Singh, Mithoon, Asees Kaur',
  album: 'Intezaar',
  description: 'A romantic waiting song.',
  moods: [{ S: 'Romantic' }, { S: 'Sad' }, { S: 'Love' }, { S: 'Emotional' }],
  filePath: path.join(__dirname, 'songs', 'Intezaar_spotdown.org.m4a'),
},
{
  songId: 'song_111',
  name: 'Is Jahaan Mein',
  artist: 'Pritam',
  album: 'Unknown Album',
  description: 'A soft emotional track.',
  moods: [{ S: 'Emotional' }, { S: 'Soft' }, { S: 'Calm' }, { S: 'Love' }],
  filePath: path.join(__dirname, 'songs', 'Is Jahaan Mein_spotdown.org.m4a'),
},
{
  songId: 'song_112',
  name: 'Is This Love',
  artist: 'Mohit Chauhan, Shreya Ghoshal, Pritam',
  album: 'Kismat Konnection',
  description: 'A romantic Bollywood song.',
  moods: [{ S: 'Romantic' }, { S: 'Love' }, { S: 'Soft' }, { S: 'Happy' }],
  filePath: path.join(__dirname, 'songs', 'Is This Love_spotdown.org.m4a'),
},
{
  songId: 'song_113',
  name: 'Ishaqzaade',
  artist: 'Amit Trivedi, Javed Ali, Shreya Ghoshal, Kausar Munir',
  album: 'Ishaqzaade',
  description: 'A rustic romantic song.',
  moods: [{ S: 'Romantic' }, { S: 'Desi' }, { S: 'Love' }, { S: 'Energetic' }],
  filePath: path.join(__dirname, 'songs', 'Ishaqzaade_spotdown.org.m4a'),
},
{
  songId: 'song_114',
  name: 'Ishq Jalakar - Karvaan',
  artist: 'Shashwat Sachdev, Shahzad Ali, Subhadeep Das Chowdhury, Armaan Khan',
  album: 'Dhurandhar',
  description: 'A soft emotional track.',
  moods: [{ S: 'Emotional' }, { S: 'Soft' }, { S: 'Sad' }, { S: 'Calm' }],
  filePath: path.join(__dirname, 'songs', 'Ishq Jalakar - Karvaan_spotdown.org.m4a'),
},
{
  songId: 'song_115',
  name: 'Ishq Mubarak',
  artist: 'Arijit Singh, Ankit Tiwari, Manoj Muntashir',
  album: 'Tum Bin 2',
  description: 'A romantic emotional song.',
  moods: [{ S: 'Romantic' }, { S: 'Emotional' }, { S: 'Love' }, { S: 'Soulful' }],
  filePath: path.join(__dirname, 'songs', 'Ishq Mubarak_spotdown.org.m4a'),
},
{
  songId: 'song_116',
  name: "It's The Time To Disco",
  artist: 'Shankar-Ehsaan-Loy, Vasundhara Das, KK, Shaan, Loy Mendonsa',
  album: 'Kal Ho Naa Ho',
  description: 'A classic Bollywood party song.',
  moods: [{ S: 'Party' }, { S: 'Dance' }, { S: 'Fun' }, { S: 'Energetic' }],
  filePath: path.join(__dirname, 'songs', "It's the Time to Disco_spotdown.org.m4a"),
},
{
  songId: 'song_117',
  name: 'Jaane Kyun Log Pyar',
  artist: 'Udit Narayan, Alka Yagnik',
  album: 'Dil Chahta Hai',
  description: 'A romantic classic.',
  moods: [{ S: 'Romantic' }, { S: 'Love' }, { S: 'Soft' }, { S: 'Happy' }],
  filePath: path.join(__dirname, 'songs', 'Jaane Kyon Log Pyar_spotdown.org.m4a'),
},
{
  songId: 'song_118',
  name: 'Jab Tak Hai Jaan',
  artist: 'A.R. Rahman, Javed Ali, Shakthisree Gopalan',
  album: 'Jab Tak Hai Jaan',
  description: 'A soulful romantic song.',
  moods: [{ S: 'Romantic' }, { S: 'Emotional' }, { S: 'Love' }, { S: 'Soulful' }],
  filePath: path.join(__dirname, 'songs', 'Jab Tak Hai Jaan_spotdown.org.m4a'),
},
{
  songId: 'song_119',
  name: 'Jack N Jill',
  artist: 'Star Boy LOC, G Skillz',
  album: 'Stream EP',
  description: 'A Punjabi hip-hop track.',
  moods: [{ S: 'HipHop' }, { S: 'Punjabi' }, { S: 'Energetic' }, { S: 'Party' }],
  filePath: path.join(__dirname, 'songs', 'Jack N Jill_spotdown.org.m4a'),
},
{
  songId: 'song_120',
  name: 'Janam Janam',
  artist: 'Pritam, Arijit Singh, Antara Mitra',
  album: 'Dilwale',
  description: 'A romantic love song.',
  moods: [{ S: 'Romantic' }, { S: 'Love' }, { S: 'Emotional' }, { S: 'Soft' }],
  filePath: path.join(__dirname, 'songs', 'Janam Janam_spotdown.org.m4a'),
},
{
  songId: 'song_121',
  name: 'Jashn-E-Bahaaraa',
  artist: 'A.R. Rahman, Javed Ali',
  album: 'Jodhaa Akbar',
  description: 'A soulful romantic classic.',
  moods: [{ S: 'Romantic' }, { S: 'Soulful' }, { S: 'Love' }, { S: 'Calm' }],
  filePath: path.join(__dirname, 'songs', 'Jashn-E-Bahaaraa_spotdown.org.m4a'),
},
{
  songId: 'song_122',
  name: 'Jeena Jeena',
  artist: 'Sachin-Jigar, Atif Aslam',
  album: 'Badlapur',
  description: 'A soft romantic song.',
  moods: [{ S: 'Romantic' }, { S: 'Soft' }, { S: 'Love' }, { S: 'Emotional' }],
  filePath: path.join(__dirname, 'songs', 'Jeena Jeena_spotdown.org.m4a'),
},
{
  songId: 'song_123',
  name: 'Jeene Laga Hoon',
  artist: 'Sachin-Jigar, Atif Aslam, Shreya Ghoshal',
  album: 'Ramaiya Vastavaiya',
  description: 'A romantic melody.',
  moods: [{ S: 'Romantic' }, { S: 'Love' }, { S: 'Happy' }, { S: 'Soft' }],
  filePath: path.join(__dirname, 'songs', 'Jeene Laga Hoon_spotdown.org.m4a'),
},
{
  songId: 'song_124',
  name: 'Jhoom Barabar Jhoom',
  artist: 'Shankar-Ehsaan-Loy, KK, Sukhwinder Singh, Mahalaxmi Iyer, Shankar Mahadevan, Gulzar',
  album: 'Jhoom Barabar Jhoom',
  description: 'A grand energetic title track.',
  moods: [{ S: 'Energetic' }, { S: 'Dance' }, { S: 'Party' }, { S: 'Grand' }],
  filePath: path.join(__dirname, 'songs', 'Jhoom Barabar Jhoom_spotdown.org.m4a'),
},
{
  songId: 'song_125',
  name: 'Jhoom Jhoom Ta Hun Main',
  artist: 'Pritam, Arijit Singh',
  album: 'Players',
  description: 'A stylish party song.',
  moods: [{ S: 'Party' }, { S: 'Dance' }, { S: 'Stylish' }, { S: 'Energetic' }],
  filePath: path.join(__dirname, 'songs', 'Jhoom Jhoom Ta Hun Main_spotdown.org.m4a'),
},
{
  songId: 'song_126',
  name: 'Jhoom',
  artist: 'Shankar-Ehsaan-Loy, Shankar Mahadevan, Gulzar',
  album: 'Jhoom Barabar Jhoom',
  description: 'A rhythmic energetic track.',
  moods: [{ S: 'Energetic' }, { S: 'Dance' }, { S: 'Fun' }, { S: 'Party' }],
  filePath: path.join(__dirname, 'songs', 'Jhoom_spotdown.org.m4a'),
},
{
  songId: 'song_127',
  name: 'Just Go To Hell Dil',
  artist: 'Amit Trivedi, Sunidhi Chauhan',
  album: 'Dear Zindagi',
  description: 'A bold emotional song.',
  moods: [{ S: 'Emotional' }, { S: 'Attitude' }, { S: 'Breakup' }, { S: 'Strong' }],
  filePath: path.join(__dirname, 'songs', 'Just Go To Hell Dil_spotdown.org.m4a'),
},
{
  songId: 'song_128',
  name: 'Kabhi Aayine Pe Likha Tujhe',
  artist: 'KK',
  album: 'Hate Story 2',
  description: 'A romantic emotional song.',
  moods: [{ S: 'Romantic' }, { S: 'Emotional' }, { S: 'Love' }, { S: 'Sad' }],
  filePath: path.join(__dirname, 'songs', 'Kabhi Aayine Pe Likha Tujhe_spotdown.org.m4a'),
},
{
  songId: 'song_129',
  name: 'Kabhi Alvida Naa Kehna',
  artist: 'Shankar-Ehsaan-Loy, Sonu Nigam, Alka Yagnik',
  album: 'Kabhi Alvida Naa Kehna',
  description: 'A soulful emotional title track.',
  moods: [{ S: 'Emotional' }, { S: 'Sad' }, { S: 'Romantic' }, { S: 'Soulful' }],
  filePath: path.join(__dirname, 'songs', 'Kabhi Alvida Naa Kehna_spotdown.org.m4a'),
},
{
  songId: 'song_130',
  name: 'Kabhi Jo Baadal Barse',
  artist: 'Arijit Singh',
  album: 'Jackpot',
  description: 'A romantic rain song.',
  moods: [{ S: 'Romantic' }, { S: 'Rain' }, { S: 'Love' }, { S: 'Emotional' }],
  filePath: path.join(__dirname, 'songs', 'Kabhi Jo Baadal Barse_spotdown.org.m4a'),
},
{
  songId: 'song_131',
  name: 'Kaisa Ye Raaz Hai',
  artist: 'Pranay, KK, Sayeed Quadri',
  album: 'Raaz - The Mystery Continues',
  description: 'A mysterious emotional track.',
  moods: [{ S: 'Mystery' }, { S: 'Emotional' }, { S: 'Dark' }, { S: 'Romantic' }],
  filePath: path.join(__dirname, 'songs', 'Kaisa Ye Raaz Hai_spotdown.org.m4a'),
},
{
  songId: 'song_132',
  name: 'Kaise Mujhe',
  artist: 'Benny Dayal, Shreya Ghoshal',
  album: 'Ghajini',
  description: 'A soft emotional romantic song.',
  moods: [{ S: 'Romantic' }, { S: 'Emotional' }, { S: 'Love' }, { S: 'Soft' }],
  filePath: path.join(__dirname, 'songs', 'Kaise Mujhe_spotdown.org.m4a'),
},
];

// ─── HELPERS ──────────────────────────────────────────────────────────────────

const getContentType = (filePath) => {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === '.m4a') return 'audio/mp4';
  if (ext === '.wav') return 'audio/wav';
  return 'audio/mpeg'; // .mp3 default
};

const uploadToS3 = async (songId, filePath) => {
  const filename = path.basename(filePath);
  const s3Key = `songs/${songId}/${filename}`;
  console.log(`  ☁️  Uploading "${filename}" → s3://${BUCKET}/${s3Key}`);

  const fileStream = fs.createReadStream(filePath);
  fileStream.on('error', (err) => { throw new Error(`Cannot read file: ${err.message}`); });

  await s3.upload({
    Bucket: BUCKET,
    Key: s3Key,
    Body: fileStream,
    ContentType: getContentType(filePath),
  }).promise();

  const songURL = `https://${BUCKET}.s3.${process.env.AWS_REGION}.amazonaws.com/${s3Key}`;
  console.log(`  ✅ Uploaded → ${songURL}`);
  return { s3Key, songURL };
};

const writeToDynamoDB = async (song, s3Key, songURL) => {
  const item = {
    PK: `SONG#${song.songId}`,
    SK: 'META',
    song_ID: song.songId,
    name: song.name,
    artist: song.artist,
    album: song.album,
    description: song.description,
    moods: song.moods,         // already [{ S: '...' }] format
    s3Key,
    songURL,
    createdAt: new Date().toISOString(),
  };

  await dynamoDB.put({
    TableName: TABLE,
    Item: item,
  }).promise();

  console.log(`  ✅ DynamoDB record saved for "${song.name}"`);
};

// ─── MAIN ─────────────────────────────────────────────────────────────────────

const seed = async () => {
  if (!BUCKET) {
    console.error('❌  S3_BUCKET is not set in your .env. Aborting.');
    process.exit(1);
  }
  console.log(`\n🚀  Seeding ${songs.length} songs into "${TABLE}" ...\n`);

  for (const song of songs) {
    console.log(`▶  "${song.name}" — ${song.artist}`);
    if (!fs.existsSync(song.filePath)) {
      console.warn(`  ⚠️  File not found: ${song.filePath} — skipping.\n`);
      continue;
    }
    try {
      const { s3Key, songURL } = await uploadToS3(song.songId, song.filePath);
      await writeToDynamoDB(song, s3Key, songURL);
      console.log(`  🎵  Done\n`);
    } catch (err) {
      console.error(`  ❌  Error processing "${song.name}": ${err.message}\n`);
    }
  }

  console.log('✅  Seeding complete.');
};

seed();